# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0cdDBFv1AgfthZ1ZC2gInmVAcBJM9rZ
"""

import streamlit as st
import requests
import os

# -----------------------------
# Hugging Face API token
# -----------------------------
HF_TOKEN = "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"

# -----------------------------
# Page setup
# -----------------------------
st.set_page_config(page_title="Persona VoiceBot", layout="centered", page_icon="🎤")
st.title("🎤 Persona VoiceBot — Hugging Face API Edition")
st.write("Ask questions, and the bot will respond like YOU.")

# -----------------------------
# Full Persona
# -----------------------------
persona_prompt = """
I am a very hardworking person. I do not easily give up when the situations are worse.
I achieve my goals, complete my works and duties even how hard it takes to reach up anywhere.
So to sum up, I can say I am not a quitter. But an evolving person who tries to learn from my situations and duties.

Focused learning. I am a person who can get my complete focus when I am trying to learn something or do my work.

The 3 areas which I wish to improve myself are my leadership qualities, my memory skills, and multitasking abilities.

A common misconception my classmates have against me is that things come easier to me or go smoothly
without any obstacles. But the reality is different. I do face obstacles and every day is a challenge.

In order to push my boundaries and limits, I keep a track of what all things should be done and act.
If the tasks have a possibility of overwhelming I mould myself according to that. I finish off my day-to-day work without keeping anything left for the day.
I am a person who prefers to complete my duties without procrastination.
"""

# -----------------------------
# User input
# -----------------------------
question = st.text_input("Ask your question:")

if st.button("Submit") and question.strip():
    prompt = persona_prompt + "\nQuestion: " + question + "\nAnswer:"

    headers = {"Authorization": f"Bearer {HF_TOKEN}"}
    API_URL = "https://api-inference.huggingface.co/models/gpt2"

    response = requests.post(API_URL, headers=headers, json={"inputs": prompt})
    output = response.json()

    try:
        answer = output[0]["generated_text"].replace(prompt, "").strip()
    except:
        answer = "Sorry, I couldn't generate a response. Try again."

    st.write("**VoiceBot Response:**", answer)

